// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa8PXBl5XJ60DNmK19gh7TKc81b4L9FfA',
    appId: '1:1046288975827:web:d0655a907a8241b0c11126',
    messagingSenderId: '1046288975827',
    projectId: 'fitnestapplication-c6306',
    authDomain: 'fitnestapplication-c6306.firebaseapp.com',
    storageBucket: 'fitnestapplication-c6306.firebasestorage.app',
    measurementId: 'G-6ZLFC13W06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLuj7fX3jbuinm-tFkiOx6vSOqQ140LA0',
    appId: '1:1046288975827:android:cce8f30431397613c11126',
    messagingSenderId: '1046288975827',
    projectId: 'fitnestapplication-c6306',
    storageBucket: 'fitnestapplication-c6306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-jvImw3APsdKods9MGC4yEe5KnxyCNQ',
    appId: '1:1046288975827:ios:99bb1c84732af9dfc11126',
    messagingSenderId: '1046288975827',
    projectId: 'fitnestapplication-c6306',
    storageBucket: 'fitnestapplication-c6306.firebasestorage.app',
    iosBundleId: 'com.example.fitnestApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr-jvImw3APsdKods9MGC4yEe5KnxyCNQ',
    appId: '1:1046288975827:ios:99bb1c84732af9dfc11126',
    messagingSenderId: '1046288975827',
    projectId: 'fitnestapplication-c6306',
    storageBucket: 'fitnestapplication-c6306.firebasestorage.app',
    iosBundleId: 'com.example.fitnestApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa8PXBl5XJ60DNmK19gh7TKc81b4L9FfA',
    appId: '1:1046288975827:web:5527e9e48ace0511c11126',
    messagingSenderId: '1046288975827',
    projectId: 'fitnestapplication-c6306',
    authDomain: 'fitnestapplication-c6306.firebaseapp.com',
    storageBucket: 'fitnestapplication-c6306.firebasestorage.app',
    measurementId: 'G-1GE4KX8EKD',
  );
}
